use crate::ast::{Program, Stmt, Expr, JsStmt, JsExpr, JsVarKind, JsTemplatePart};
use std::fs;

pub struct NodeBuilder {
    output: String,
}

impl NodeBuilder {
    pub fn new() -> Self {
        Self { output: String::new() }
    }

    pub fn build(&mut self, program: &Program) -> String {
        self.output.push_str("// Generated by Ema Compiler for Node.js\n");
        self.output.push_str("const fs = require('fs');\n");
        self.output.push_str("const http = require('http');\n\n");

        for stmt in &program.statements {
            self.compile_stmt(stmt);
        }

        self.output.clone()
    }

    fn compile_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::VarDecl { name, value, .. } => {
                let val = self.compile_expr(value);
                self.output.push_str(&format!("let {} = {};\n", name, val));
            }
            Stmt::StateDecl { name, value, .. } => {
                let val = self.compile_expr(value);
                self.output.push_str(&format!("let {} = {}; // State indexed\n", name, val));
            }
            Stmt::PrintStmt(expr, _) => {
                let val = self.compile_expr(expr);
                self.output.push_str(&format!("console.log({});\n", val));
            }
            Stmt::ServerBlock(stmts, _) => {
                self.output.push_str("// @server block\n");
                for s in stmts { self.compile_stmt(s); }
            }
            Stmt::FnDecl { name, params, body, is_async, .. } => {
                let prefix = if *is_async { "async " } else { "" };
                let p_names: Vec<String> = params.iter().map(|(n, _)| n.clone()).collect();
                self.output.push_str(&format!("{}{}function {}({}) {{\n", prefix, if *is_async { "" } else { "" }, name, p_names.join(", ")));
                for s in body { self.compile_stmt(s); }
                self.output.push_str("}\n");
            }
            Stmt::IfStmt { condition, then_branch, else_branch, .. } => {
                let cond = self.compile_expr(condition);
                self.output.push_str(&format!("if ({}) {{\n", cond));
                for s in then_branch { self.compile_stmt(s); }
                self.output.push_str("}");
                if let Some(eb) = else_branch {
                    self.output.push_str(" else {\n");
                    for s in eb { self.compile_stmt(s); }
                    self.output.push_str("}\n");
                } else {
                    self.output.push_str("\n");
                }
            }
            Stmt::ExprStmt(expr, _) => {
                let val = self.compile_expr(expr);
                self.output.push_str(&format!("{};\n", val));
            }
            _ => {
                // Placeholder for other markers
            }
        }
    }

    fn compile_expr(&mut self, expr: &Expr) -> String {
        match expr {
            Expr::IntLit(v, _) => v.to_string(),
            Expr::StringLit(v, _) => format!("\"{}\"", v),
            Expr::FloatLit(v, _) => v.to_string(),
            Expr::BoolLit(v, _) => v.to_string(),
            Expr::Identifier(v, _) => v.clone(),
            Expr::Binary { left, op, right, .. } => {
                let l = self.compile_expr(left);
                let r = self.compile_expr(right);
                let op_str = match op {
                    crate::ast::BinaryOp::Add => "+",
                    crate::ast::BinaryOp::Sub => "-",
                    crate::ast::BinaryOp::Mul => "*",
                    crate::ast::BinaryOp::Div => "/",
                    crate::ast::BinaryOp::EqEq => "===",
                    crate::ast::BinaryOp::BangEq => "!==",
                    crate::ast::BinaryOp::Less => "<",
                    crate::ast::BinaryOp::LessEq => "<=",
                    crate::ast::BinaryOp::Greater => ">",
                    crate::ast::BinaryOp::GreaterEq => ">=",
                };
                format!("({} {} {})", l, op_str, r)
            }
            Expr::Call { callee, args, .. } => {
                let c = self.compile_expr(callee);
                let a: Vec<String> = args.iter().map(|arg| self.compile_expr(arg)).collect();
                format!("{}({})", c, a.join(", "))
            }
            Expr::NamespaceCall { namespace, method, .. } => {
                if namespace == "std::http" && method == "serve" {
                    return "http.createServer((req, res) => { res.end('EMA Server (Node.js)'); }).listen(3001)".to_string();
                }
                format!("{}.{}(...)", namespace, method)
            }
            Expr::JsAst { program, .. } => {
                let mut out = String::new();
                for s in &program.body {
                    out.push_str(&self.compile_js_stmt(s));
                    out.push('\n');
                }
                out
            }
            Expr::PhpAst { program, .. } => {
                let mut out = String::new();
                for s in &program.body {
                    out.push_str(&self.compile_php_stmt(s));
                    out.push('\n');
                }
                out
            }
            Expr::ClientScript(stmts, _) | Expr::ServerScript(stmts, _) => {
                let mut out = String::new();
                for s in stmts { self.compile_stmt(s); }
                out
            }
            _ => "null".to_string(),
        }
    }

    fn compile_js_stmt(&self, stmt: &JsStmt) -> String {
        match stmt {
            JsStmt::Expr(expr, _) => format!("{};", self.compile_js_expr(expr)),
            JsStmt::VarDecl { kind, pattern, value, .. } => {
                let k_str = match kind {
                    JsVarKind::Const => "const",
                    JsVarKind::Let => "let",
                    JsVarKind::Var => "var",
                };
                let p_str = match pattern {
                    crate::ast::JsPattern::Ident(s, _) => s.clone(),
                    _ => "/* pattern */".to_string(), // Simplified
                };
                if let Some(v) = value {
                    format!("{} {} = {};", k_str, p_str, self.compile_js_expr(v))
                } else {
                    format!("{} {};", k_str, p_str)
                }
            }
            JsStmt::Return(expr, _) => {
                if let Some(e) = expr {
                    format!("return {};", self.compile_js_expr(e))
                } else {
                    "return;".to_string()
                }
            }
            JsStmt::Block { body, .. } => {
                let mut out = "{ \n".to_string();
                for s in body {
                    out.push_str(&self.compile_js_stmt(s));
                    out.push('\n');
                }
                out.push_str(" }");
                out
            }
            JsStmt::If { condition, then_branch, else_branch, .. } => {
                let mut out = format!("if ({}) {}", self.compile_js_expr(condition), self.compile_js_stmt(then_branch));
                if let Some(e) = else_branch {
                    out.push_str(" else ");
                    out.push_str(&self.compile_js_stmt(e));
                }
                out
            }
            JsStmt::While { condition, body, .. } => {
                format!("while ({}) {}", self.compile_js_expr(condition), self.compile_js_stmt(body))
            }
            JsStmt::For { init, condition, update, body, .. } => {
                let init_s = match init {
                    Some(s) => {
                        let mut s2 = self.compile_js_stmt(s);
                        if s2.ends_with(';') { s2.pop(); }
                        s2
                    }
                    None => "".to_string(),
                };
                let cond_s = condition.as_ref().map(|e| self.compile_js_expr(e)).unwrap_or_else(|| "".to_string());
                let upd_s = update.as_ref().map(|e| self.compile_js_expr(e)).unwrap_or_else(|| "".to_string());
                format!("for ({}; {}; {}) {}", init_s, cond_s, upd_s, self.compile_js_stmt(body))
            }
            JsStmt::ClassDecl { name, extends, body, .. } => {
                let ext_str = if let Some(e) = extends { format!(" extends {}", e) } else { "".to_string() };
                let mut out = format!("class {}{} {{\n", name, ext_str);
                for s in body {
                    if let JsStmt::FunctionDecl { name, params, body, is_async, .. } = s {
                        let prefix = if *is_async { "async " } else { "" };
                        let p_names: Vec<String> = params.iter().map(|p| p.name.clone()).collect();
                        out.push_str(&format!("  {}{}({}) {}\n", prefix, name, p_names.join(", "), self.compile_js_stmt(body)));
                    } else {
                        out.push_str(&self.compile_js_stmt(s));
                        out.push('\n');
                    }
                }
                out.push_str(" }");
                out
            }
            JsStmt::FunctionDecl { name, params, body, is_async, .. } => {
                let prefix = if *is_async { "async " } else { "" };
                let p_names: Vec<String> = params.iter().map(|p| p.name.clone()).collect();
                format!("{}{}function {}({}) {}", prefix, "", name, p_names.join(", "), self.compile_js_stmt(body))
            }
            JsStmt::Switch { discriminant, cases, default, .. } => {
                let mut out = format!("switch ({}) {{\n", self.compile_js_expr(discriminant));
                for (cond, stmts) in cases {
                    out.push_str(&format!("  case {}:\n", self.compile_js_expr(cond)));
                    for s in stmts {
                        out.push_str("    ");
                        out.push_str(&self.compile_js_stmt(s));
                        out.push('\n');
                    }
                }
                if let Some(stmts) = default {
                    out.push_str("  default:\n");
                    for s in stmts {
                        out.push_str("    ");
                        out.push_str(&self.compile_js_stmt(s));
                        out.push('\n');
                    }
                }
                out.push_str("}");
                out
            }
            JsStmt::Break(_) => "break;".to_string(),
            JsStmt::Continue(_) => "continue;".to_string(),
            _ => "// Other statement\n".to_string(),
        }
    }

    fn compile_js_expr(&self, expr: &JsExpr) -> String {
        match expr {
            JsExpr::Ident(s, _) => s.clone(),
            JsExpr::String(s, _) => format!("\"{}\"", s),
            JsExpr::Number(n, _) => n.to_string(),
            JsExpr::Bool(b, _) => b.to_string(),
            JsExpr::Null(_) => "null".to_string(),
            JsExpr::This(_) => "this".to_string(),
            JsExpr::Super(_) => "super".to_string(),
            JsExpr::Binary { left, op, right, .. } => {
                format!("({} {} {})", self.compile_js_expr(left), op, self.compile_js_expr(right))
            }
            JsExpr::Unary { op, expr, .. } => {
                format!("{}({})", op, self.compile_js_expr(expr))
            }
            JsExpr::Assign { target, value, .. } => {
                format!("{} = {}", self.compile_js_expr(target), self.compile_js_expr(value))
            }
            JsExpr::Call { callee, args, .. } => {
                let a: Vec<String> = args.iter().map(|arg| self.compile_js_expr(arg)).collect();
                format!("{}({})", self.compile_js_expr(callee), a.join(", "))
            }
            JsExpr::Member { object, property, .. } => {
                format!("{}.{}", self.compile_js_expr(object), property)
            }
            JsExpr::Update { op, is_prefix, expr, .. } => {
                if *is_prefix {
                    format!("{}{}", op, self.compile_js_expr(expr))
                } else {
                    format!("{}{}", self.compile_js_expr(expr), op)
                }
            }
            JsExpr::New { callee, args, .. } => {
                let a: Vec<String> = args.iter().map(|arg| self.compile_js_expr(arg)).collect();
                format!("new {}({})", self.compile_js_expr(callee), a.join(", "))
            }
            JsExpr::ObjectLit { props, .. } => {
                let p: Vec<String> = props.iter().map(|(k, v)| format!("{}: {}", k, self.compile_js_expr(v))).collect();
                format!("{{ {} }}", p.join(", "))
            }
            JsExpr::ArrayLit { items, .. } => {
                let i: Vec<String> = items.iter().map(|item| self.compile_js_expr(item)).collect();
                format!("[{}]", i.join(", "))
            }
            JsExpr::TemplateLit { parts, .. } => {
                let mut out = "`".to_string();
                for p in parts {
                    match p {
                        JsTemplatePart::Str(s) => out.push_str(s),
                        JsTemplatePart::Expr(e) => out.push_str(&format!("${{{}}}", self.compile_js_expr(e))),
                    }
                }
                out.push('`');
                out
            }
            JsExpr::Await { expr, .. } => format!("await {}", self.compile_js_expr(expr)),
            _ => "null".to_string(),
        }
    }

    fn compile_php_stmt(&self, stmt: &crate::ast::PhpStmt) -> String {
        use crate::ast::PhpStmt;
        match stmt {
            PhpStmt::Echo(expr, _) => format!("console.log({});", self.compile_php_expr(expr)),
            PhpStmt::Print(expr, _) => format!("console.log({});", self.compile_php_expr(expr)),
            PhpStmt::Assign { name, value, .. } => format!("let {} = {};", name, self.compile_php_expr(value)),
            PhpStmt::Expr(expr, _) => format!("{};", self.compile_php_expr(expr)),
            PhpStmt::If { condition, then_branch, else_branch, .. } => {
                let mut out = format!("if ({}) {{\n", self.compile_php_expr(condition));
                for s in then_branch { out.push_str(&self.compile_php_stmt(s)); out.push('\n'); }
                out.push('}');
                if let Some(eb) = else_branch {
                    out.push_str(" else {\n");
                    for s in eb { out.push_str(&self.compile_php_stmt(s)); out.push('\n'); }
                    out.push('}');
                }
                out
            }
            PhpStmt::While { condition, body, .. } => {
                let mut out = format!("while ({}) {{\n", self.compile_php_expr(condition));
                for s in body { out.push_str(&self.compile_php_stmt(s)); out.push('\n'); }
                out.push('}');
                out
            }
            _ => "// Unsupported PHP statement\n".to_string(),
        }
    }

    fn compile_php_expr(&self, expr: &crate::ast::PhpExpr) -> String {
        use crate::ast::PhpExpr;
        match expr {
            PhpExpr::Var(name, _) => name.clone(),
            PhpExpr::String(s, _) => format!("\"{}\"", s),
            PhpExpr::Int(v, _) => v.to_string(),
            PhpExpr::Float(v, _) => v.to_string(),
            PhpExpr::Bool(b, _) => b.to_string(),
            PhpExpr::Null(_) => "null".to_string(),
            PhpExpr::Binary { left, op, right, .. } => {
                let o = if op == "." { "+" } else { op };
                format!("({} {} {})", self.compile_php_expr(left), o, self.compile_php_expr(right))
            }
            PhpExpr::ArrayLit { items, .. } => {
                if items.iter().any(|(k, _)| k.is_some()) {
                    // Associative array -> JS object
                    let mut props = Vec::new();
                    for (k, v) in items {
                        let key = match k {
                            Some(PhpExpr::String(s, _)) => format!("\"{}\"", s),
                            Some(PhpExpr::Int(i, _)) => i.to_string(),
                            Some(e) => self.compile_php_expr(e), // For computed keys
                            None => "".to_string(), // Should not happen for associative
                        };
                        props.push(format!("{}: {}", key, self.compile_php_expr(v)));
                    }
                    format!("{{ {} }}", props.join(", "))
                } else {
                    // Simple array -> JS array
                    let elements: Vec<String> = items.iter().map(|(_, v)| self.compile_php_expr(v)).collect();
                    format!("[{}]", elements.join(", "))
                }
            }
            PhpExpr::ObjectLit { props, .. } => {
                let p: Vec<String> = props.iter().map(|(k, v)| format!("{}: {}", k, self.compile_php_expr(v))).collect();
                format!("{{ {} }}", p.join(", "))
            }
            PhpExpr::Call { name, args, .. } => {
                let a: Vec<String> = args.iter().map(|arg| self.compile_php_expr(arg)).collect();
                format!("{}({})", name, a.join(", "))
            }
            PhpExpr::ArrowFn { params, body, .. } => {
                format!("(({}) => {})", params.join(", "), self.compile_php_expr(body))
            }
            PhpExpr::Match { discriminant, cases, default, .. } => {
                let mut out = format!("((_arg) => {{\n  switch(_arg) {{\n");
                for (cond, res) in cases {
                    out.push_str(&format!("    case {}: return {};\n", self.compile_php_expr(cond), self.compile_php_expr(res)));
                }
                if let Some(d) = default {
                    out.push_str(&format!("    default: return {};\n", self.compile_php_expr(d)));
                }
                out.push_str("  }\n})(_val)");
                out.replace("_val", &self.compile_php_expr(discriminant))
            }
            PhpExpr::Coalesce { left, right, .. } => {
                format!("({} ?? {})", self.compile_php_expr(left), self.compile_php_expr(right))
            }
            PhpExpr::Member { object, property, .. } => {
                format!("{}.{}", self.compile_php_expr(object), property)
            }
            PhpExpr::NullsafeMember { object, property, .. } => {
                format!("{}?.{}", self.compile_php_expr(object), property)
            }
            PhpExpr::CoalesceAssign { name, value, .. } => {
                format!("{} ??= {}", name, self.compile_php_expr(value))
            }
            PhpExpr::Index { target, index, .. } => {
                format!("{}[{}]", self.compile_php_expr(target), self.compile_php_expr(index))
            }
        }
    }
}
